# Generated by Django 4.0.1 on 2022-02-22 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import emails.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='<django.db.models.fields.related.ForeignKey>')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='%Y/%m_%d/', validators=[emails.validators.file_size])),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('is_inbox', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('is_trash', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(blank=True, to='emails.Category')),
                ('receiver', models.ManyToManyField(related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='emails.signature')),
            ],
        ),
    ]
