# Generated by Django 4.0.2 on 2022-02-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='active_phone',
            field=models.BooleanField(default=True),
        ),
    ]
