# Generated by Django 4.0.2 on 2022-02-22 15:53

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_active_email_alter_user_active_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, error_messages={'unique': 'This email already has an account'}, max_length=150, null=True, unique=True, validators=[accounts.validators.valid_email]),
        ),
    ]
