# Generated by Django 4.0.2 on 2022-02-22 16:33

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_address',
            field=models.CharField(blank=True, error_messages={'unique': 'Ops tekrarie'}, max_length=150, null=True, unique=True, validators=[accounts.validators.valid_email], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
