# Generated by Django 4.0.2 on 2022-02-22 19:04

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_email_address_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_address',
            field=models.CharField(blank=True, error_messages={'unique': 'This email already has an account '}, max_length=150, null=True, unique=True, validators=[accounts.validators.valid_email], verbose_name='email address'),
        ),
    ]
