# Generated by Django 4.0.2 on 2022-02-22 21:30

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, error_messages={'unique': 'This phone number already has an account'}, max_length=12, null=True, unique=True, validators=[accounts.validators.valid_phone]),
        ),
    ]
